; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:weactstudio_esp32c3coreboard]
platform = espressif32
board = weactstudio_esp32c3coreboard
framework = arduino

monitor_speed = 115200

; 【关键修改】开启大程序模式，支持最大 3MB 的程序
board_build.partitions = huge_app.csv

lib_deps = 
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
	olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
	bblanchon/ArduinoJson @ ^6.21.6
	tzapu/WiFiManager@^2.0.17

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1